jwt:
  secretKey: 'afakmnbnrioagenffewr!$!@$!!~~#noesingsaklgamslfksafmasfnafoiewnfalkfsdanklasghoasfjaoiwen'

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

