spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

  web:
    cors:
      allowed-origins: http://localhost:3000

  datasource:
    writer:
      url: jdbc:h2:mem:testdb
      username: sa
    reader:
      url: jdbc:h2:mem:testdb
      username: sa

  security:
    oauth2:
      client:
        provider:
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
jwt:
  secret-key: ${SECRET_KEY}
  access:
    expiration-time: 1h
  refresh:
    expiration-time: 14d

