openapi: 3.0.1
info:
  title: API 규격
  description: API 규격 문서
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: 로컬 서버
tags: []
paths:
  /board/articles:
    get:
      tags:
      - 게시판 > 게시글
      summary: 게시글 목록 조회
      description: 게시글 목록 조회
      operationId: article-rest-controller-test/게시글 목록 조회
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board-articles-1499844002'
              examples:
                article-rest-controller-test/게시글 목록 조회:
                  value: |-
                    [ {
                      "id" : 1,
                      "title" : "제목 A",
                      "category" : "IT"
                    }, {
                      "id" : 2,
                      "title" : "제목 B",
                      "category" : "IT"
                    }, {
                      "id" : 3,
                      "title" : "제목 C",
                      "category" : "스포츠"
                    } ]
    post:
      tags:
      - 게시판 > 게시글
      summary: 게시글 생성
      description: 게시글 생성
      operationId: article-rest-controller-test/게시글 생성
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/board-articles-1450587914'
            examples:
              article-rest-controller-test/게시글 생성:
                value: |-
                  {
                    "title" : "테스트 제목",
                    "content" : "테스트 내용",
                    "categoryId" : 10
                  }
      responses:
        "201":
          description: "201"
          headers:
            Location:
              description: 게시글 URI
              schema:
                type: string
  /board/categories:
    get:
      tags:
      - 게시판 > 카테고리
      summary: 카테고리 조회
      description: 카테고리 조회
      operationId: category-rest-controller-test/카테고리 조회
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board-categories-1002833915'
              examples:
                category-rest-controller-test/카테고리 조회:
                  value: |-
                    [ {
                      "id" : 1,
                      "name" : "컴퓨터",
                      "children" : [ {
                        "id" : 2,
                        "name" : "맥북"
                      } ]
                    } ]
    post:
      tags:
      - 게시판 > 카테고리
      summary: 카테고리 생성
      description: 카테고리 생성
      operationId: category-rest-controller-test/카테고리 생성
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/board-categories1661442423'
            examples:
              category-rest-controller-test/카테고리 생성:
                value: |-
                  {
                    "name" : "IT",
                    "parentId" : 1
                  }
      responses:
        "201":
          description: "201"
  /board/articles/{articleId}:
    get:
      tags:
      - 게시판 > 게시글
      summary: 게시글 조회
      description: 게시글 조회
      operationId: article-rest-controller-test/게시글 조회
      parameters:
      - name: articleId
        in: path
        description: 게시글 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board-articles-articleId1038093111'
              examples:
                article-rest-controller-test/게시글 조회:
                  value: |-
                    {
                      "id" : 1,
                      "title" : "제목",
                      "content" : "내용",
                      "category" : "IT"
                    }
    put:
      tags:
      - 게시판 > 게시글
      summary: 게시글 수정
      description: 게시글 수정
      operationId: article-rest-controller-test/게시글 수정
      parameters:
      - name: articleId
        in: path
        description: 게시글 ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/board-articles-1450587914'
            examples:
              article-rest-controller-test/게시글 수정:
                value: |-
                  {
                    "title" : "수정 제목",
                    "content" : "수정 내용",
                    "categoryId" : 10
                  }
      responses:
        "200":
          description: "200"
    delete:
      tags:
      - 게시판 > 게시글
      summary: 게시글 삭제
      description: Soft delete 수행
      operationId: article-rest-controller-test/게시글 삭제
      parameters:
      - name: articleId
        in: path
        description: 게시글 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
  /board/category/{id}:
    put:
      tags:
      - 게시판 > 카테고리
      summary: 카테고리 수정
      description: 카테고리 수정
      operationId: category-rest-controller-test/카테고리 수정
      parameters:
      - name: id
        in: path
        description: 카테고리 ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/board-categories1661442423'
            examples:
              category-rest-controller-test/카테고리 수정:
                value: |-
                  {
                    "name" : "수정",
                    "parentId" : 1
                  }
      responses:
        "200":
          description: "200"
    delete:
      tags:
      - 게시판 > 카테고리
      summary: 카테고리 삭제
      description: Hard delete 수행
      operationId: category-rest-controller-test/카테고리 삭제
      parameters:
      - name: id
        in: path
        description: 카테고리 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
  /user/members:
    get:
      tags:
      - 사용자
      summary: 사용자 목록 조회
      description: 사용자 목록 조회
      operationId: member-rest-controller-test/사용자 목록 조회
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-members-1036020352'
              examples:
                member-rest-controller-test/사용자 목록 조회:
                  value: |-
                    [ {
                      "id" : 1,
                      "name" : "홍길동",
                      "email" : "adminA@sat.com",
                      "createdDateTime" : "2024-01-01T07:00:00"
                    }, {
                      "id" : 2,
                      "name" : "홍동길",
                      "email" : "adminB@sat.com",
                      "createdDateTime" : "2024-01-01T07:00:00"
                    }, {
                      "id" : 3,
                      "name" : "홍길돔",
                      "email" : "adminC@sat.com",
                      "createdDateTime" : "2024-01-01T07:00:00"
                    } ]
  /user/members/me:
    get:
      tags:
      - 사용자
      summary: 사용자 목록 조회
      description: 사용자 목록 조회
      operationId: member-rest-controller-test/자신의 정보 조회
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user-members-me-115117825'
              examples:
                member-rest-controller-test/자신의 정보 조회:
                  value: |-
                    {
                      "id" : 1,
                      "name" : "홍길동",
                      "nickname" : "홍길동",
                      "email" : "admin@sat.com"
                    }
components:
  schemas:
    board-categories1661442423:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: 카테고리 이름
        parentId:
          type: number
          description: 카테고리 부모 ID
          nullable: true
    board-articles-1499844002:
      type: array
      items:
        required:
        - category
        - id
        - title
        type: object
        properties:
          id:
            type: number
            description: 게시글 ID
          category:
            type: string
            description: 카테고리
          title:
            type: string
            description: 게시글 제목
    board-articles-articleId1038093111:
      required:
      - category
      - content
      - id
      - title
      type: object
      properties:
        id:
          type: number
          description: 게시글 ID
        category:
          type: string
          description: 카테고리
        title:
          type: string
          description: 게시글 제목
        content:
          type: string
          description: 게시글 내용
    board-categories-1002833915:
      type: array
      items:
        required:
        - id
        - name
        type: object
        properties:
          children:
            type: array
            items:
              required:
              - id
              - name
              type: object
              properties:
                name:
                  type: string
                  description: 자식 카테고리 이름
                id:
                  type: number
                  description: 자식 카테고리 ID
          name:
            type: string
            description: 카테고리 이름
          id:
            type: number
            description: 카테고리 ID
    user-members-me-115117825:
      required:
      - email
      - id
      - name
      - nickname
      type: object
      properties:
        nickname:
          type: string
          description: 닉네임
        name:
          type: string
          description: 이름
        id:
          type: number
          description: 사용자 ID
        email:
          type: string
          description: 이메일
    board-articles-1450587914:
      required:
      - categoryId
      - content
      - title
      type: object
      properties:
        title:
          type: string
          description: 게시글 제목
        categoryId:
          type: number
          description: 카테고리 ID
        content:
          type: string
          description: 게시글 내용
    user-members-1036020352:
      type: array
      items:
        required:
        - createdDateTime
        - email
        - id
        - name
        type: object
        properties:
          name:
            type: string
            description: 이름
          createdDateTime:
            type: string
            description: 가입 시간
          id:
            type: number
            description: 사용자 ID
          email:
            type: string
            description: 이메일
