name: SAT-CI
run-name: Build
on:
  push:
    branches: [main, feature/*]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app
        run: ./gradlew bootJar

      - name: Generate image tag
        id: image-tag
        run: |
          date=$(date +%Y%m%d.%H%M)
          commit_id=${{ github.sha }}
          image_tag=kwongyujung/sat:$date-${commit_id:0:4}-latest
          echo "image-tag=$image_tag" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.image-tag.outputs.image-tag }}
